const express = require("express");

const BillPayment = require("../models/BillPayment");
const Expense = require("../models/Expense");
const Bill = require("../models/Bill");
const IncomeSource = require("../models/IncomeSource");
const { authRequired } = require("../middleware/auth");
const { getBudgetPeriod } = require("../utils/paycheckUtils");

const router = express.Router();

// GET — all bill payments for user, optionally filtered by dueDate range
router.get("/", authRequired, async (req, res) => {
  try {
    const query = { user: req.userId };
    if (req.query.from || req.query.to) {
      query.dueDate = {};
      if (req.query.from) query.dueDate.$gte = new Date(req.query.from);
      if (req.query.to) query.dueDate.$lte = new Date(req.query.to);
    }
    const payments = await BillPayment.find(query).sort({ dueDate: -1 });
    res.json(payments);
  } catch (error) {
    console.error("Error fetching bill payments:", error);
    res.status(500).json({ error: "Server error" });
  }
});

// POST — create or update a bill payment (mark as paid)
router.post("/", authRequired, async (req, res) => {
  try {
    const { billId, dueDate, paidDate, paidAmount, note } = req.body;
    if (!billId || !dueDate || !paidDate || paidAmount == null) {
      return res.status(400).json({ error: "billId, dueDate, paidDate, and paidAmount are required." });
    }

    const payment = await BillPayment.findOneAndUpdate(
      { user: req.userId, bill: billId, dueDate: new Date(dueDate + "T12:00:00") },
      { paidDate: new Date(paidDate + "T12:00:00"), paidAmount: Number(paidAmount), note: note || "" },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    // Ensure user field is set on upsert
    if (!payment.user) {
      payment.user = req.userId;
      await payment.save();
    }
    // Auto-create expense if paid in a different period than due date
    try {
      const sources = await IncomeSource.find({ user: req.userId, isActive: true });
      if (sources.length > 0) {
        const dueDateObj = new Date(dueDate + "T12:00:00");
        const paidDateObj = new Date(paidDate + "T12:00:00");
        const duePeriod = getBudgetPeriod(sources, dueDateObj);
        const paidPeriod = getBudgetPeriod(sources, paidDateObj);

        // Check if they're in different periods
        const sameStart = duePeriod && paidPeriod &&
          duePeriod.start.getTime() === paidPeriod.start.getTime();

        if (duePeriod && paidPeriod && !sameStart) {
          // Different periods — create an expense in the paid-date period
          const bill = await Bill.findById(billId);
          const billName = bill ? bill.name : "Bill";

          // Check if auto-expense already exists to avoid duplicates
          const existing = await Expense.findOne({
            user: req.userId,
            date: paidDateObj,
            description: { $regex: `${billName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')} \\(paid early\\)` },
            autoGenerated: true,
          });

          if (!existing) {
            await Expense.create({
              user: req.userId,
              userId: req.userId,
              date: paidDateObj,
              amount: Number(paidAmount),
              category: "Bills",
              description: `${billName} (paid early)`,
              note: `Early payment — due ${dueDateObj.toLocaleDateString("en-US", { month: "short", day: "numeric" })}`,
              autoGenerated: true,
            });
          }
        }
      }
    } catch (err) {
      console.error("Auto-expense creation error:", err);
      // Non-critical — don't fail the payment save
    }

    res.json(payment);
  } catch (error) {
    console.error("Error saving bill payment:", error);
    res.status(500).json({ error: "Server error" });
  }
});

// DELETE — remove a bill payment by ID (must belong to user)
router.delete("/:id", authRequired, async (req, res) => {
  try {
    const deleted = await BillPayment.findOneAndDelete({
      _id: req.params.id,
      user: req.userId,
    });
    if (!deleted) return res.status(404).json({ error: "Bill payment not found" });

    // Cascade: delete linked auto-generated expense
    try {
      if (deleted.paidDate && deleted.bill) {
        const bill = await Bill.findById(deleted.bill);
        const billName = bill ? bill.name : "";
        if (billName) {
          await Expense.deleteMany({
            user: req.userId,
            autoGenerated: true,
            description: { $regex: billName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + " \\(paid early\\)" },
            date: deleted.paidDate,
          });
        }
      }
    } catch { /* non-critical */ }

    res.json({ success: true });
  } catch (error) {
    console.error("Error deleting bill payment:", error);
    res.status(500).json({ error: "Server error" });
  }
});

module.exports = router;
