// Shared service for marking a bill paid/unpaid. The HTTP routes in
// routes/billPaymentRoutes.js (POST / DELETE /:id) and the new
// routes/billRoutes.js (PATCH /:id/paid) both delegate here so the
// paidEarly routing + auto-expense creation + cascade-delete logic
// only lives in one place.
//
// IMPORTANT: this module is a thin re-export of the exact write path
// used by billPaymentRoutes.js POST/DELETE. The finance engine's
// paidEarly routing already fires via the Expense auto-creation here
// when due-period != paid-period, and the spendable-balance pipeline
// already reacts to Expense changes — so callers get the full
// behavior for free without this helper touching financeEngine.js.

const BillPayment = require("../models/BillPayment");
const Expense = require("../models/Expense");
const Bill = require("../models/Bill");
const IncomeSource = require("../models/IncomeSource");
const { getBudgetPeriod } = require("./paycheckUtils");

/**
 * Mark a bill paid for a given due date.
 * Idempotent via findOneAndUpdate upsert on the
 * (user, bill, dueDate) composite unique index. Auto-creates an
 * Expense in the paid-date's pay period when it differs from the
 * due-date's pay period (the paidEarly / paid-late routing).
 *
 * Returns the BillPayment document.
 *
 * @param {string} userId
 * @param {{ billId: string, dueDate: string|Date, paidDate: string|Date,
 *           paidAmount: number, note?: string }} input
 */
async function markBillPaid(userId, input) {
  const { billId, dueDate, paidDate, paidAmount, note } = input;
  if (!billId || !dueDate || !paidDate || paidAmount == null) {
    const err = new Error("billId, dueDate, paidDate, and paidAmount are required.");
    err.status = 400;
    throw err;
  }
  // Normalize date-only strings to Dates at local noon. The existing
  // routes used the same "T12:00:00" convention; preserve exactly so
  // the composite unique index keeps working across old + new writers.
  const toDate = (v) => {
    if (v instanceof Date) return v;
    if (/^\d{4}-\d{2}-\d{2}$/.test(String(v))) return new Date(`${v}T12:00:00`);
    return new Date(v);
  };
  const dueDateObj = toDate(dueDate);
  const paidDateObj = toDate(paidDate);

  const payment = await BillPayment.findOneAndUpdate(
    { user: userId, bill: billId, dueDate: dueDateObj },
    { paidDate: paidDateObj, paidAmount: Number(paidAmount), note: note || "" },
    { upsert: true, new: true, setDefaultsOnInsert: true },
  );
  if (!payment.user) {
    payment.user = userId;
    await payment.save();
  }

  // Mirror the self-describing fields on the Bill doc.
  try {
    await Bill.findOneAndUpdate(
      { _id: billId, user: userId },
      { $set: { paid: true, markedPaidAt: new Date() } },
    );
  } catch { /* non-critical */ }

  // paidEarly routing: the finance engine now picks up cross-period
  // paid-early bills via sumBillsInPeriod's paid-early loop (keyed on
  // BillPayment.paidDate), so we no longer need to create a mirror
  // Expense row here. The auto-generated "(paid early)" expenses
  // were showing up in the Calendar day sheet's expense list (and
  // in the ExpenseHistory list) as if they were user-logged spending,
  // which is the double-display bug the user reported. Keeping only
  // the BillPayment record is enough for the balance math and avoids
  // the display pollution. The unmark-side delete below still runs
  // against legacy auto-Expense rows left in the DB from before this
  // change.

  return payment;
}

/**
 * Unmark a bill payment. Deletes the BillPayment row and cascades to
 * remove any auto-generated "paid early" expense the POST side created.
 */
async function unmarkBillPayment(userId, { billPaymentId, billId, dueDate } = {}) {
  let deleted;
  if (billPaymentId) {
    deleted = await BillPayment.findOneAndDelete({ _id: billPaymentId, user: userId });
  } else if (billId && dueDate) {
    const dueDateObj = dueDate instanceof Date
      ? dueDate
      : /^\d{4}-\d{2}-\d{2}$/.test(String(dueDate))
        ? new Date(`${dueDate}T12:00:00`)
        : new Date(dueDate);
    deleted = await BillPayment.findOneAndDelete({
      user: userId, bill: billId, dueDate: dueDateObj,
    });
  } else {
    const err = new Error("billPaymentId or (billId + dueDate) required.");
    err.status = 400;
    throw err;
  }
  if (!deleted) return null;

  try {
    if (deleted.paidDate && deleted.bill) {
      const bill = await Bill.findOne({ _id: deleted.bill, user: userId });
      const billName = bill ? bill.name : "";
      if (billName) {
        await Expense.deleteMany({
          user: userId,
          autoGenerated: true,
          description: { $regex: billName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + " \\(paid early\\)" },
          date: deleted.paidDate,
        });
      }
    }
  } catch { /* non-critical */ }

  try {
    await Bill.findOneAndUpdate(
      { _id: deleted.bill, user: userId },
      { $set: { paid: false, markedPaidAt: null } },
    );
  } catch { /* non-critical */ }

  return deleted;
}

module.exports = { markBillPaid, unmarkBillPayment };
