// scripts/duplicate-audit.js
//
// Read-only duplicate audit for a single user's financial collections.
// Usage:
//   MONGO_URI=... TARGET_EMAIL=torresjosebryan@gmail.com node scripts/duplicate-audit.js
//
// Never deletes. Outputs a Markdown report to docs/duplicate-audit.md
// that lists candidate duplicates across Bills, Expenses, PaymentPlan
// installments, and IncomeSources. Re-run after re-onboarding or any
// time you suspect data duplication.

require("dotenv").config();
const mongoose = require("mongoose");
const fs = require("fs");
const path = require("path");

const Bill = require("../models/Bill");
const Expense = require("../models/Expense");
const PaymentPlan = require("../models/PaymentPlan");
const IncomeSource = require("../models/IncomeSource");
const User = require("../models/User");

const TARGET_EMAIL = process.env.TARGET_EMAIL;
if (!TARGET_EMAIL) {
  console.error("Set TARGET_EMAIL=<user email> before running.");
  process.exit(1);
}

const fmtDate = (d) => {
  if (!d) return "(null)";
  const dt = new Date(d);
  return `${dt.getUTCFullYear()}-${String(dt.getUTCMonth() + 1).padStart(2, "0")}-${String(dt.getUTCDate()).padStart(2, "0")}`;
};
const fmtAmt = (n) => `$${(Number(n) || 0).toFixed(2)}`;

async function main() {
  await mongoose.connect(process.env.MONGO_URI, {});
  const user = await User.findOne({ email: TARGET_EMAIL }).select("_id email createdAt currentBalance");
  if (!user) {
    console.error(`No user found with email ${TARGET_EMAIL}`);
    await mongoose.disconnect();
    process.exit(2);
  }

  const lines = [];
  lines.push(`# Duplicate audit — ${TARGET_EMAIL}`);
  lines.push("");
  lines.push(`- User _id: \`${user._id}\``);
  lines.push(`- createdAt: ${fmtDate(user.createdAt)}`);
  lines.push(`- currentBalance: ${fmtAmt(user.currentBalance)}`);
  lines.push(`- Generated: ${new Date().toISOString()}`);
  lines.push("");

  // ── Bills: (name, amount, dueDayOfMonth) collisions ────────────────
  const bills = await Bill.find({ user: user._id });
  lines.push("## Bills");
  lines.push(`Total bills: ${bills.length}`);
  const billKey = (b) => `${(b.name || "").trim().toLowerCase()}|${Number(b.amount).toFixed(2)}|${b.dueDayOfMonth || b.dueDay || 0}`;
  const billGroups = {};
  bills.forEach((b) => {
    const k = billKey(b);
    (billGroups[k] = billGroups[k] || []).push(b);
  });
  const dupBills = Object.values(billGroups).filter((g) => g.length > 1);
  if (!dupBills.length) lines.push("- No duplicate bills found.");
  else {
    lines.push(`- Duplicate bill groups: ${dupBills.length}`);
    dupBills.forEach((g) => {
      lines.push(`  - **${g[0].name}** ${fmtAmt(g[0].amount)} due day ${g[0].dueDayOfMonth || g[0].dueDay} × ${g.length}`);
      g.forEach((b) => lines.push(`    - \`${b._id}\` created ${fmtDate(b.createdAt)}`));
    });
  }
  lines.push("");

  // ── Expenses: (date, amount, category, description) exact match ───
  const expenses = await Expense.find({ $or: [{ user: user._id }, { userId: user._id }] });
  lines.push("## Expenses");
  lines.push(`Total expense rows: ${expenses.length}`);
  const autoGenCount = expenses.filter((e) => e.autoGenerated).length;
  lines.push(`- Auto-generated (billPaymentService legacy): ${autoGenCount}`);
  const expKey = (e) => `${fmtDate(e.date)}|${Number(e.amount).toFixed(2)}|${(e.category || "").toLowerCase()}|${(e.description || "").trim().toLowerCase()}`;
  const expGroups = {};
  expenses.forEach((e) => {
    const k = expKey(e);
    (expGroups[k] = expGroups[k] || []).push(e);
  });
  const dupExps = Object.values(expGroups).filter((g) => g.length > 1);
  if (!dupExps.length) lines.push("- No duplicate expenses found.");
  else {
    lines.push(`- Duplicate expense groups: ${dupExps.length}`);
    dupExps.forEach((g) => {
      lines.push(`  - ${fmtDate(g[0].date)} — ${g[0].description || "(no desc)"} ${fmtAmt(g[0].amount)} [${g[0].category}] × ${g.length}`);
      g.forEach((e) => lines.push(`    - \`${e._id}\`${e.autoGenerated ? " (auto)" : ""} created ${fmtDate(e.createdAt)}`));
    });
  }
  lines.push("");

  // ── Plan installments: (planId, date, amount) collisions ──────────
  const plans = await PaymentPlan.find({ userId: user._id });
  lines.push("## Plan installments");
  lines.push(`Total plans: ${plans.length}`);
  let dupInstCount = 0;
  plans.forEach((plan) => {
    const groups = {};
    (plan.payments || []).forEach((p) => {
      const k = `${fmtDate(p.date)}|${Number(p.amount).toFixed(2)}`;
      (groups[k] = groups[k] || []).push(p);
    });
    const dups = Object.values(groups).filter((g) => g.length > 1);
    if (dups.length) {
      dupInstCount += dups.length;
      lines.push(`- Plan **${plan.name}** (\`${plan._id}\`):`);
      dups.forEach((g) => {
        lines.push(`  - ${fmtDate(g[0].date)} × ${fmtAmt(g[0].amount)} × ${g.length} installments`);
        g.forEach((p) => lines.push(`    - id=\`${p.id}\` paid=${!!p.paid}${p.paidDate ? ` paidDate=${fmtDate(p.paidDate)}` : ""}`));
      });
    }
  });
  if (!dupInstCount) lines.push("- No duplicate plan installments found.");
  lines.push("");

  // ── Income sources: (source name, amount, frequency) ──────────────
  const sources = await IncomeSource.find({ user: user._id });
  lines.push("## Income sources");
  lines.push(`Total sources: ${sources.length}`);
  const srcKey = (s) => `${(s.name || "").trim().toLowerCase()}|${Number(s.amount).toFixed(2)}|${s.frequency}`;
  const srcGroups = {};
  sources.forEach((s) => {
    const k = srcKey(s);
    (srcGroups[k] = srcGroups[k] || []).push(s);
  });
  const dupSrc = Object.values(srcGroups).filter((g) => g.length > 1);
  if (!dupSrc.length) lines.push("- No duplicate income sources found.");
  else {
    dupSrc.forEach((g) => {
      lines.push(`  - **${g[0].name}** ${fmtAmt(g[0].amount)} ${g[0].frequency} × ${g.length}`);
      g.forEach((s) => lines.push(`    - \`${s._id}\` isPrimary=${!!s.isPrimary} isActive=${!!s.isActive}`));
    });
  }
  lines.push("");

  // ── Advisory: BillPayments with orphan or missing linked Bill ─────
  const BillPayment = require("../models/BillPayment");
  const billPayments = await BillPayment.find({ user: user._id });
  const billIds = new Set(bills.map((b) => String(b._id)));
  const orphanPayments = billPayments.filter((bp) => !billIds.has(String(bp.bill)));
  lines.push("## Bill payments");
  lines.push(`Total payment records: ${billPayments.length}`);
  if (orphanPayments.length) {
    lines.push(`- ⚠ Orphan payments (bill no longer exists): ${orphanPayments.length}`);
    orphanPayments.forEach((bp) => {
      lines.push(`  - \`${bp._id}\` dueDate=${fmtDate(bp.dueDate)} paidDate=${fmtDate(bp.paidDate)} ${fmtAmt(bp.paidAmount)}`);
    });
  } else {
    lines.push("- No orphan payments.");
  }
  lines.push("");

  // Write report
  const outDir = path.resolve(__dirname, "..", "docs");
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, "duplicate-audit.md");
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${outPath}`);
  console.log(`- Duplicate bill groups:       ${dupBills.length}`);
  console.log(`- Duplicate expense groups:    ${dupExps.length}`);
  console.log(`- Duplicate plan installments: ${dupInstCount}`);
  console.log(`- Duplicate income sources:    ${dupSrc.length}`);
  console.log(`- Orphan bill payments:        ${orphanPayments.length}`);
  console.log(`- Auto-generated expenses:     ${autoGenCount}`);

  await mongoose.disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
