const mongoose = require("mongoose");

const expenseSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      index: true,
      default() {
        return this.user;
      },
    },
    date: {
      type: Date,
      required: true,
    },
    amount: {
      type: Number,
      required: true,
      min: 0,
    },
    category: {
      type: String,
      required: true,
      default: "Other",
    },
    description: {
      type: String,
      trim: true,
    },
    autoGenerated: { type: Boolean, default: false },
    // §6 — expenses carry their own paid flag. Expenses dated today
    // auto-mark paid on create (the user just spent the money). Future-
    // dated expenses stay unpaid until the user marks them paid from the
    // outstanding queue or the expense row itself.
    paid: { type: Boolean, default: false },
    markedPaidAt: { type: Date, default: null },
  },
  { timestamps: true }
);

expenseSchema.pre("validate", function alignLegacyFields(next) {
  if (!this.user && this.userId) {
    this.user = this.userId;
  }
  next();
});

module.exports = mongoose.model("Expense", expenseSchema);
