const mongoose = require("mongoose");

const transactionSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    type: {
      type: String,
      enum: ["expense", "savings", "investment"],
      required: true,
    },
    label: { type: String, required: true },
    amount: { type: Number, required: true },
    date: { type: Date, required: true },
    paycheckIndex: { type: Number },
    meta: {
      category: String,
      platform: String,
      ruleId: { type: mongoose.Schema.Types.ObjectId, ref: "Rule", default: null },
      autoGenerated: { type: Boolean, default: false },
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Transaction", transactionSchema);
