const mongoose = require("mongoose");

const UserSchema = new mongoose.Schema(
  {
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    name: { type: String, required: true },
    firstName: { type: String, trim: true },
    lastName: { type: String, trim: true },
    phone: { type: String, trim: true },
    dateOfBirth: { type: Date },
    passwordHash: { type: String, required: true },
    onboardingComplete: { type: Boolean, default: false },
    isPremium: { type: Boolean, default: false },
    premiumSince: { type: Date },
    stripeCustomerId: { type: String },
    stripeSubscriptionId: { type: String },
    locale: { type: String, default: "en" },
    subscriptionStatus: {
      type: String,
      enum: ["free", "trialing", "premium", "premium_monthly", "premium_annual", "expired"],
      default: "free",
    },
    trialStartDate: { type: Date },
    trialEndDate: { type: Date },
    notificationPrefs: {
      billReminders: { type: Boolean, default: true },
      paydayReminders: { type: Boolean, default: true },
      reminderDaysBefore: { type: Number, default: 3 },
      lowBalanceWarning: { type: Boolean, default: false },
      lowBalanceThreshold: { type: Number, default: 100 },
    },
    incomeSettings: {
      amount: { type: Number, default: 0 },
      frequency: { type: String, enum: ["weekly", "biweekly", "monthly"], default: "biweekly" },
      lastPaycheckDate: { type: Date },
    },
    incomeType: { type: String, enum: ["fixed", "variable"], default: "fixed" },
    totalSavings: { type: Number, default: 0 },
    extraIncomeCount: { type: Number, default: 0 },
    extraIncomeYearReset: { type: Number },
    emailVerified: { type: Boolean, default: false },
    verificationToken: { type: String },
    verificationTokenExpiry: { type: Date },
    loginHistory: [{
      timestamp: { type: Date, default: Date.now },
      ip: { type: String },
      userAgent: { type: String },
    }],
    isAdmin: { type: Boolean, default: false },
    currentBalance: { type: Number, default: 0 },
    initialSavings: { type: Number, default: 0 },
    verificationCode: { type: String },
    verificationCodeExpiry: { type: Date },
    passwordResetToken: { type: String },
    passwordResetExpiry: { type: Date },
    resetCode: { type: String },
    resetCodeExpiry: { type: Date },
    twoFactorEnabled: { type: Boolean, default: false },
    twoFactorOTP: { type: String },
    twoFactorOTPExpiry: { type: Date },
    deleteCode: { type: String },
    deleteCodeExpiry: { type: Date },
    billReminderEnabled: { type: Boolean, default: true },
    lowBalanceAlertEnabled: { type: Boolean, default: true },
    lowBalanceThreshold: { type: Number, default: 150 },
  },
  { timestamps: true }
);

module.exports = mongoose.model("User", UserSchema);
